### send the post request
POST http://localhost:3003/api/blogs 
Content-Type:  application/json

{
    "title": "my first request",
    "author": "Yuvraj Singh",
    "url": "https://github.com/yuvrajsteve-cmyk/fullstackopen-part4",
    "likes": 10
}

### send the get request
GET http://localhost:3003/api/blogs 
Content-Type: application/json

